#include "argparse.h"
#include "build_config.h"
#include "fwd.h"
#include "machine/cg.h"
#include "machine/dfa.h"
#include "machine/nfa.h"
#include "regex.h"
#include "utils.h"
#include <algorithm>
#include "argparse.h"
#include <bitset>
#include <cassert>
#include <cctype>
#include <climits>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <deque>
#include <format>
#include <fstream>
#include <functional>
#include <iostream>
#include <istream>
#include <list>
#include <memory>
#include <ostream>
#include <print>
#include <queue>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
