/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 104
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_section_separator = 1,
  sym__raw_line = 2,
  sym_blank_line = 3,
  sym_comment = 4,
  sym__eol = 5,
  anon_sym_MACRO = 6,
  anon_sym_STATE = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_UNKNOWN = 10,
  anon_sym_ERROR = 11,
  anon_sym_RULE = 12,
  sym_priority = 13,
  sym_identifier = 14,
  sym_action = 15,
  anon_sym_SLASH = 16,
  anon_sym_LPAREN = 17,
  anon_sym_RPAREN = 18,
  anon_sym_STAR = 19,
  anon_sym_PLUS = 20,
  anon_sym_QMARK = 21,
  sym_alternation_bar = 22,
  sym_wildcard = 23,
  anon_sym_LBRACK = 24,
  anon_sym_CARET = 25,
  anon_sym_RBRACK = 26,
  anon_sym_DASH = 27,
  sym_escape = 28,
  sym_codepoint_escape = 29,
  sym_literal_char = 30,
  anon_sym_DQUOTE = 31,
  aux_sym_string_literal_token1 = 32,
  sym_source_file = 33,
  sym_preamble = 34,
  sym_epilogue = 35,
  sym_macro_def = 36,
  sym_state_def = 37,
  sym_unknown_directive = 38,
  sym_error_directive = 39,
  sym_rule = 40,
  sym__pattern = 41,
  sym_regex = 42,
  sym__regex_term = 43,
  sym_group = 44,
  sym_quantifier = 45,
  sym_char_class = 46,
  sym__char_class_item = 47,
  sym_char_range = 48,
  sym_macro_ref = 49,
  sym_string_literal = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_preamble_repeat1 = 52,
  aux_sym_state_def_repeat1 = 53,
  aux_sym_regex_repeat1 = 54,
  aux_sym_char_class_repeat1 = 55,
  aux_sym_string_literal_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_section_separator] = "section_separator",
  [sym__raw_line] = "_raw_line",
  [sym_blank_line] = "blank_line",
  [sym_comment] = "comment",
  [sym__eol] = "_eol",
  [anon_sym_MACRO] = "MACRO",
  [anon_sym_STATE] = "STATE",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_UNKNOWN] = "UNKNOWN",
  [anon_sym_ERROR] = "ERROR",
  [anon_sym_RULE] = "RULE",
  [sym_priority] = "priority",
  [sym_identifier] = "identifier",
  [sym_action] = "action",
  [anon_sym_SLASH] = "/",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_QMARK] = "\?",
  [sym_alternation_bar] = "alternation_bar",
  [sym_wildcard] = "wildcard",
  [anon_sym_LBRACK] = "[",
  [anon_sym_CARET] = "^",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH] = "-",
  [sym_escape] = "escape",
  [sym_codepoint_escape] = "codepoint_escape",
  [sym_literal_char] = "literal_char",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_source_file] = "source_file",
  [sym_preamble] = "preamble",
  [sym_epilogue] = "epilogue",
  [sym_macro_def] = "macro_def",
  [sym_state_def] = "state_def",
  [sym_unknown_directive] = "unknown_directive",
  [sym_error_directive] = "error_directive",
  [sym_rule] = "rule",
  [sym__pattern] = "_pattern",
  [sym_regex] = "regex",
  [sym__regex_term] = "_regex_term",
  [sym_group] = "group",
  [sym_quantifier] = "quantifier",
  [sym_char_class] = "char_class",
  [sym__char_class_item] = "_char_class_item",
  [sym_char_range] = "char_range",
  [sym_macro_ref] = "macro_ref",
  [sym_string_literal] = "string_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_preamble_repeat1] = "preamble_repeat1",
  [aux_sym_state_def_repeat1] = "state_def_repeat1",
  [aux_sym_regex_repeat1] = "regex_repeat1",
  [aux_sym_char_class_repeat1] = "char_class_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_section_separator] = sym_section_separator,
  [sym__raw_line] = sym__raw_line,
  [sym_blank_line] = sym_blank_line,
  [sym_comment] = sym_comment,
  [sym__eol] = sym__eol,
  [anon_sym_MACRO] = anon_sym_MACRO,
  [anon_sym_STATE] = anon_sym_STATE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_UNKNOWN] = anon_sym_UNKNOWN,
  [anon_sym_ERROR] = anon_sym_ERROR,
  [anon_sym_RULE] = anon_sym_RULE,
  [sym_priority] = sym_priority,
  [sym_identifier] = sym_identifier,
  [sym_action] = sym_action,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [sym_alternation_bar] = sym_alternation_bar,
  [sym_wildcard] = sym_wildcard,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_escape] = sym_escape,
  [sym_codepoint_escape] = sym_codepoint_escape,
  [sym_literal_char] = sym_literal_char,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_source_file] = sym_source_file,
  [sym_preamble] = sym_preamble,
  [sym_epilogue] = sym_epilogue,
  [sym_macro_def] = sym_macro_def,
  [sym_state_def] = sym_state_def,
  [sym_unknown_directive] = sym_unknown_directive,
  [sym_error_directive] = sym_error_directive,
  [sym_rule] = sym_rule,
  [sym__pattern] = sym__pattern,
  [sym_regex] = sym_regex,
  [sym__regex_term] = sym__regex_term,
  [sym_group] = sym_group,
  [sym_quantifier] = sym_quantifier,
  [sym_char_class] = sym_char_class,
  [sym__char_class_item] = sym__char_class_item,
  [sym_char_range] = sym_char_range,
  [sym_macro_ref] = sym_macro_ref,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_preamble_repeat1] = aux_sym_preamble_repeat1,
  [aux_sym_state_def_repeat1] = aux_sym_state_def_repeat1,
  [aux_sym_regex_repeat1] = aux_sym_regex_repeat1,
  [aux_sym_char_class_repeat1] = aux_sym_char_class_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_section_separator] = {
    .visible = true,
    .named = true,
  },
  [sym__raw_line] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_MACRO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UNKNOWN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ERROR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RULE] = {
    .visible = true,
    .named = false,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [sym_alternation_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_codepoint_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_preamble] = {
    .visible = true,
    .named = true,
  },
  [sym_epilogue] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_def] = {
    .visible = true,
    .named = true,
  },
  [sym_state_def] = {
    .visible = true,
    .named = true,
  },
  [sym_unknown_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_error_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [sym__regex_term] = {
    .visible = false,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_char_class] = {
    .visible = true,
    .named = true,
  },
  [sym__char_class_item] = {
    .visible = false,
    .named = true,
  },
  [sym_char_range] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preamble_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_state_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regex_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_char_class_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_action = 1,
  field_epilogue = 2,
  field_name = 3,
  field_pattern = 4,
  field_preamble = 5,
  field_priority = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_action] = "action",
  [field_epilogue] = "epilogue",
  [field_name] = "name",
  [field_pattern] = "pattern",
  [field_preamble] = "preamble",
  [field_priority] = "priority",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 1},
  [10] = {.index = 12, .length = 2},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_epilogue, 2},
  [1] =
    {field_pattern, 0},
  [2] =
    {field_preamble, 0},
  [3] =
    {field_pattern, 1},
  [4] =
    {field_action, 1},
    {field_pattern, 0},
  [6] =
    {field_epilogue, 3},
  [7] =
    {field_epilogue, 3},
    {field_preamble, 0},
  [9] =
    {field_name, 1},
    {field_pattern, 2},
  [11] =
    {field_name, 1},
  [12] =
    {field_pattern, 2},
    {field_priority, 1},
  [14] =
    {field_action, 2},
    {field_pattern, 1},
  [16] =
    {field_epilogue, 4},
    {field_preamble, 0},
  [18] =
    {field_action, 3},
    {field_pattern, 2},
    {field_priority, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 9,
  [13] = 8,
  [14] = 11,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 15,
  [22] = 16,
  [23] = 17,
  [24] = 19,
  [25] = 20,
  [26] = 26,
  [27] = 18,
  [28] = 26,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 38,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 48,
  [51] = 51,
  [52] = 52,
  [53] = 47,
  [54] = 45,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 16,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 70,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 96,
  [100] = 100,
  [101] = 96,
  [102] = 83,
  [103] = 83,
};

static const TSCharacterRange sym_escape_character_set_1[] = {
  {'"', '"'}, {'(', '+'}, {'-', '7'}, {'?', '?'}, {'D', 'D'}, {'S', 'S'}, {'W', 'W'}, {'[', '^'},
  {'a', 'a'}, {'d', 'd'}, {'f', 'f'}, {'n', 'n'}, {'r', 't'}, {'v', 'x'}, {'|', '|'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(49);
      ADVANCE_MAP(
        '\n', 54,
        '\r', 1,
        '"', 93,
        '%', 15,
        '(', 69,
        ')', 70,
        '*', 71,
        '+', 72,
        '-', 79,
        '.', 75,
        '/', 68,
        '?', 73,
        'E', 34,
        'M', 19,
        'R', 38,
        'S', 36,
        'U', 26,
        '[', 76,
        '\\', 43,
        ']', 78,
        '^', 77,
        '{', 59,
        '|', 74,
        '}', 60,
        '\t', 2,
        ' ', 2,
        '#', 4,
        ';', 4,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(54);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 54,
        '\r', 1,
        '"', 93,
        '%', 15,
        '(', 69,
        ')', 70,
        '*', 71,
        '+', 72,
        '-', 79,
        '.', 75,
        '/', 68,
        '?', 73,
        'E', 34,
        'M', 19,
        'R', 38,
        'S', 36,
        'U', 26,
        '[', 76,
        '\\', 43,
        ']', 78,
        '^', 77,
        '{', 59,
        '|', 74,
        '}', 60,
        '\t', 2,
        ' ', 2,
        '#', 4,
        ';', 4,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 54,
        '\r', 1,
        '"', 93,
        '%', 15,
        '/', 68,
        'E', 34,
        'M', 19,
        'R', 38,
        'S', 36,
        'U', 26,
        '}', 60,
        '\t', 3,
        ' ', 3,
        '#', 4,
        ';', 4,
      );
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(50);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(50);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '%') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '%') ADVANCE(52);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(56);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(67);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 14:
      if (lookahead == '"') ADVANCE(93);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(94);
      END_STATE();
    case 15:
      if (lookahead == '%') ADVANCE(51);
      END_STATE();
    case 16:
      ADVANCE_MAP(
        '(', 69,
        ')', 70,
        '*', 71,
        '+', 72,
        '.', 75,
        '?', 73,
        '[', 76,
        '\\', 92,
        '{', 59,
        '|', 74,
        '\t', 86,
        ' ', 86,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 17:
      ADVANCE_MAP(
        '(', 69,
        '*', 71,
        '+', 72,
        '.', 75,
        '/', 68,
        '?', 73,
        '[', 76,
        '\\', 92,
        '{', 59,
        '|', 74,
        '\t', 87,
        ' ', 87,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(79);
      if (lookahead == '\\') ADVANCE(92);
      if (lookahead == ']') ADVANCE(78);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 19:
      if (lookahead == 'A') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'A') ADVANCE(37);
      END_STATE();
    case 21:
      if (lookahead == 'C') ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(63);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(58);
      END_STATE();
    case 24:
      if (lookahead == 'K') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 'L') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == 'N') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == 'N') ADVANCE(61);
      END_STATE();
    case 28:
      if (lookahead == 'N') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'O') ADVANCE(57);
      END_STATE();
    case 30:
      if (lookahead == 'O') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 'O') ADVANCE(33);
      END_STATE();
    case 32:
      if (lookahead == 'R') ADVANCE(31);
      END_STATE();
    case 33:
      if (lookahead == 'R') ADVANCE(62);
      END_STATE();
    case 34:
      if (lookahead == 'R') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'R') ADVANCE(29);
      END_STATE();
    case 36:
      if (lookahead == 'T') ADVANCE(20);
      END_STATE();
    case 37:
      if (lookahead == 'T') ADVANCE(23);
      END_STATE();
    case 38:
      if (lookahead == 'U') ADVANCE(25);
      END_STATE();
    case 39:
      if (lookahead == 'W') ADVANCE(27);
      END_STATE();
    case 40:
      if (lookahead == '\\') ADVANCE(92);
      if (lookahead == ']') ADVANCE(78);
      if (lookahead == '^') ADVANCE(77);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 41:
      if (lookahead == '\\') ADVANCE(92);
      if (lookahead == ']') ADVANCE(78);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 42:
      if (lookahead == '\\') ADVANCE(92);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(44);
      if (lookahead == 'x') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(82);
      if (set_contains(sym_escape_character_set_1, 15, lookahead)) ADVANCE(80);
      END_STATE();
    case 44:
      if (lookahead == '{') ADVANCE(47);
      END_STATE();
    case 45:
      if (lookahead == '}') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(45);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(45);
      END_STATE();
    case 48:
      if (eof) ADVANCE(49);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_section_separator);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_section_separator);
      if (lookahead == '\n') ADVANCE(50);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_section_separator);
      if (lookahead == '\n') ADVANCE(50);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__raw_line);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_MACRO);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_STATE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_UNKNOWN);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_ERROR);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RULE);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_priority);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_action);
      if (lookahead == '\r') ADVANCE(67);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_action);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_alternation_bar);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_escape);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_escape);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_escape);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_codepoint_escape);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_literal_char);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_literal_char);
      ADVANCE_MAP(
        '(', 69,
        ')', 70,
        '*', 71,
        '+', 72,
        '.', 75,
        '?', 73,
        '[', 76,
        '\\', 92,
        '{', 59,
        '|', 74,
        '\t', 86,
        ' ', 86,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_literal_char);
      ADVANCE_MAP(
        '(', 69,
        '*', 71,
        '+', 72,
        '.', 75,
        '/', 68,
        '?', 73,
        '[', 76,
        '\\', 92,
        '{', 59,
        '|', 74,
        '\t', 87,
        ' ', 87,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == '-') ADVANCE(79);
      if (lookahead == '\\') ADVANCE(92);
      if (lookahead == ']') ADVANCE(78);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == '\\') ADVANCE(92);
      if (lookahead == ']') ADVANCE(78);
      if (lookahead == '^') ADVANCE(77);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == '\\') ADVANCE(92);
      if (lookahead == ']') ADVANCE(78);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == '\\') ADVANCE(92);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == 'u') ADVANCE(44);
      if (lookahead == 'x') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(82);
      if (set_contains(sym_escape_character_set_1, 15, lookahead)) ADVANCE(80);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(94);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 17},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 17},
  [21] = {.lex_state = 17},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 17},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 40},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 40},
  [45] = {.lex_state = 41},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 41},
  [48] = {.lex_state = 41},
  [49] = {.lex_state = 41},
  [50] = {.lex_state = 41},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 41},
  [54] = {.lex_state = 41},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 18},
  [57] = {.lex_state = 14},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 14},
  [60] = {.lex_state = 41},
  [61] = {.lex_state = 14},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 41},
  [64] = {.lex_state = 48},
  [65] = {.lex_state = 48},
  [66] = {.lex_state = 48},
  [67] = {.lex_state = 48},
  [68] = {.lex_state = 42},
  [69] = {.lex_state = 7},
  [70] = {.lex_state = 48},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 48},
  [73] = {.lex_state = 12},
  [74] = {.lex_state = 12},
  [75] = {.lex_state = 12},
  [76] = {.lex_state = 12},
  [77] = {.lex_state = 12},
  [78] = {.lex_state = 12},
  [79] = {.lex_state = 12},
  [80] = {.lex_state = 12},
  [81] = {.lex_state = 12},
  [82] = {.lex_state = 12},
  [83] = {.lex_state = 13},
  [84] = {.lex_state = 13},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 13},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 13},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 13},
  [95] = {.lex_state = 13},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 13},
  [98] = {.lex_state = 13},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 13},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 13},
  [103] = {.lex_state = 13},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_section_separator] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
    [anon_sym_MACRO] = ACTIONS(1),
    [anon_sym_STATE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_UNKNOWN] = ACTIONS(1),
    [anon_sym_ERROR] = ACTIONS(1),
    [anon_sym_RULE] = ACTIONS(1),
    [sym_priority] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [sym_alternation_bar] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [sym_codepoint_escape] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(86),
    [sym_preamble] = STATE(88),
    [aux_sym_preamble_repeat1] = STATE(69),
    [sym_section_separator] = ACTIONS(3),
    [sym__raw_line] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(7), 1,
      sym_section_separator,
    ACTIONS(11), 1,
      anon_sym_MACRO,
    ACTIONS(13), 1,
      anon_sym_STATE,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 2,
      sym_blank_line,
      sym_comment,
    STATE(73), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(4), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [42] = 11,
    ACTIONS(11), 1,
      anon_sym_MACRO,
    ACTIONS(13), 1,
      anon_sym_STATE,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_section_separator,
    ACTIONS(27), 2,
      sym_blank_line,
      sym_comment,
    STATE(73), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(5), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [84] = 11,
    ACTIONS(29), 1,
      sym_section_separator,
    ACTIONS(34), 1,
      anon_sym_MACRO,
    ACTIONS(37), 1,
      anon_sym_STATE,
    ACTIONS(40), 1,
      anon_sym_UNKNOWN,
    ACTIONS(43), 1,
      anon_sym_ERROR,
    ACTIONS(46), 1,
      anon_sym_RULE,
    ACTIONS(49), 1,
      anon_sym_SLASH,
    ACTIONS(52), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 2,
      sym_blank_line,
      sym_comment,
    STATE(73), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(4), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [126] = 11,
    ACTIONS(11), 1,
      anon_sym_MACRO,
    ACTIONS(13), 1,
      anon_sym_STATE,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(55), 1,
      sym_section_separator,
    ACTIONS(9), 2,
      sym_blank_line,
      sym_comment,
    STATE(73), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(4), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [168] = 11,
    ACTIONS(11), 1,
      anon_sym_MACRO,
    ACTIONS(13), 1,
      anon_sym_STATE,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      sym_section_separator,
    ACTIONS(59), 2,
      sym_blank_line,
      sym_comment,
    STATE(73), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(2), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [210] = 7,
    ACTIONS(61), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_SLASH,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(69), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(9), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [243] = 7,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    ACTIONS(83), 1,
      anon_sym_LBRACK,
    ACTIONS(79), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(81), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(11), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [276] = 7,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(88), 1,
      anon_sym_SLASH,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      anon_sym_LBRACK,
    ACTIONS(93), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(96), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(9), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [309] = 7,
    ACTIONS(61), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(102), 1,
      anon_sym_SLASH,
    ACTIONS(67), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(104), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(7), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [342] = 7,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LBRACK,
    ACTIONS(106), 1,
      anon_sym_RPAREN,
    ACTIONS(79), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(108), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(12), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [375] = 7,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(116), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(119), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(12), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [408] = 7,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LBRACK,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(79), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(127), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(14), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [441] = 7,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(79), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(108), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(12), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [474] = 1,
    ACTIONS(131), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [489] = 1,
    ACTIONS(133), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [504] = 1,
    ACTIONS(135), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [519] = 1,
    ACTIONS(137), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [534] = 1,
    ACTIONS(139), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [549] = 1,
    ACTIONS(141), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [564] = 1,
    ACTIONS(131), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [579] = 1,
    ACTIONS(133), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [594] = 1,
    ACTIONS(135), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [609] = 1,
    ACTIONS(139), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [624] = 1,
    ACTIONS(141), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [639] = 1,
    ACTIONS(143), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [654] = 1,
    ACTIONS(137), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [669] = 1,
    ACTIONS(143), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [684] = 1,
    ACTIONS(145), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [698] = 1,
    ACTIONS(147), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [712] = 1,
    ACTIONS(149), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [726] = 1,
    ACTIONS(151), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [740] = 1,
    ACTIONS(153), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [754] = 1,
    ACTIONS(155), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [768] = 1,
    ACTIONS(157), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [781] = 1,
    ACTIONS(159), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [794] = 1,
    ACTIONS(161), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [807] = 5,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(165), 1,
      anon_sym_CARET,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(47), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [828] = 1,
    ACTIONS(171), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [841] = 1,
    ACTIONS(173), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [854] = 1,
    ACTIONS(175), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [867] = 1,
    ACTIONS(177), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [880] = 1,
    ACTIONS(179), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [893] = 5,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      anon_sym_CARET,
    ACTIONS(183), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(53), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [914] = 4,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(49), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [932] = 6,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    ACTIONS(189), 1,
      anon_sym_RULE,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
    STATE(46), 2,
      sym_rule,
      aux_sym_state_def_repeat1,
    STATE(73), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
  [954] = 4,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(49), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [972] = 4,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(45), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [990] = 4,
    ACTIONS(200), 1,
      anon_sym_LBRACE,
    ACTIONS(203), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(49), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1008] = 4,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(208), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(54), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1026] = 6,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    STATE(46), 2,
      sym_rule,
      aux_sym_state_def_repeat1,
    STATE(73), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
  [1048] = 6,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
    STATE(51), 2,
      sym_rule,
      aux_sym_state_def_repeat1,
    STATE(73), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
  [1070] = 4,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(208), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(49), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1088] = 4,
    ACTIONS(163), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(49), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1106] = 4,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(216), 1,
      sym_priority,
    STATE(74), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
  [1121] = 2,
    ACTIONS(220), 1,
      anon_sym_DASH,
    ACTIONS(218), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [1132] = 4,
    ACTIONS(225), 1,
      anon_sym_DQUOTE,
    ACTIONS(227), 1,
      aux_sym_string_literal_token1,
    STATE(57), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(222), 2,
      sym_escape,
      sym_codepoint_escape,
  [1146] = 3,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(80), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
  [1158] = 4,
    ACTIONS(232), 1,
      anon_sym_DQUOTE,
    ACTIONS(234), 1,
      aux_sym_string_literal_token1,
    STATE(57), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(230), 2,
      sym_escape,
      sym_codepoint_escape,
  [1172] = 1,
    ACTIONS(236), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [1180] = 4,
    ACTIONS(240), 1,
      anon_sym_DQUOTE,
    ACTIONS(242), 1,
      aux_sym_string_literal_token1,
    STATE(59), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(238), 2,
      sym_escape,
      sym_codepoint_escape,
  [1194] = 3,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(77), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
  [1206] = 1,
    ACTIONS(133), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [1214] = 4,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
    ACTIONS(246), 1,
      sym__raw_line,
    STATE(72), 1,
      aux_sym_preamble_repeat1,
    STATE(85), 1,
      sym_epilogue,
  [1227] = 4,
    ACTIONS(246), 1,
      sym__raw_line,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
    STATE(72), 1,
      aux_sym_preamble_repeat1,
    STATE(91), 1,
      sym_epilogue,
  [1240] = 4,
    ACTIONS(246), 1,
      sym__raw_line,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
    STATE(72), 1,
      aux_sym_preamble_repeat1,
    STATE(89), 1,
      sym_epilogue,
  [1253] = 4,
    ACTIONS(246), 1,
      sym__raw_line,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
    STATE(72), 1,
      aux_sym_preamble_repeat1,
    STATE(93), 1,
      sym_epilogue,
  [1266] = 1,
    ACTIONS(254), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [1272] = 3,
    ACTIONS(256), 1,
      sym_section_separator,
    ACTIONS(258), 1,
      sym__raw_line,
    STATE(71), 1,
      aux_sym_preamble_repeat1,
  [1282] = 3,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
    ACTIONS(262), 1,
      sym__raw_line,
    STATE(70), 1,
      aux_sym_preamble_repeat1,
  [1292] = 3,
    ACTIONS(260), 1,
      sym_section_separator,
    ACTIONS(265), 1,
      sym__raw_line,
    STATE(71), 1,
      aux_sym_preamble_repeat1,
  [1302] = 3,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
    ACTIONS(270), 1,
      sym__raw_line,
    STATE(70), 1,
      aux_sym_preamble_repeat1,
  [1312] = 2,
    ACTIONS(272), 1,
      sym__eol,
    ACTIONS(274), 1,
      sym_action,
  [1319] = 2,
    ACTIONS(276), 1,
      sym__eol,
    ACTIONS(278), 1,
      sym_action,
  [1326] = 2,
    ACTIONS(280), 1,
      sym__eol,
    ACTIONS(282), 1,
      sym_action,
  [1333] = 2,
    ACTIONS(284), 1,
      sym__eol,
    ACTIONS(286), 1,
      sym_action,
  [1340] = 2,
    ACTIONS(288), 1,
      sym__eol,
    ACTIONS(290), 1,
      sym_action,
  [1347] = 2,
    ACTIONS(292), 1,
      sym__eol,
    ACTIONS(294), 1,
      sym_action,
  [1354] = 2,
    ACTIONS(296), 1,
      sym__eol,
    ACTIONS(298), 1,
      sym_action,
  [1361] = 2,
    ACTIONS(300), 1,
      sym__eol,
    ACTIONS(302), 1,
      sym_action,
  [1368] = 2,
    ACTIONS(304), 1,
      sym__eol,
    ACTIONS(306), 1,
      sym_action,
  [1375] = 2,
    ACTIONS(308), 1,
      sym__eol,
    ACTIONS(310), 1,
      sym_action,
  [1382] = 1,
    ACTIONS(312), 1,
      sym_identifier,
  [1386] = 1,
    ACTIONS(314), 1,
      sym__eol,
  [1390] = 1,
    ACTIONS(316), 1,
      ts_builtin_sym_end,
  [1394] = 1,
    ACTIONS(318), 1,
      ts_builtin_sym_end,
  [1398] = 1,
    ACTIONS(320), 1,
      sym__eol,
  [1402] = 1,
    ACTIONS(322), 1,
      sym_section_separator,
  [1406] = 1,
    ACTIONS(324), 1,
      ts_builtin_sym_end,
  [1410] = 1,
    ACTIONS(326), 1,
      sym__eol,
  [1414] = 1,
    ACTIONS(328), 1,
      ts_builtin_sym_end,
  [1418] = 1,
    ACTIONS(330), 1,
      anon_sym_LBRACE,
  [1422] = 1,
    ACTIONS(332), 1,
      ts_builtin_sym_end,
  [1426] = 1,
    ACTIONS(334), 1,
      sym_identifier,
  [1430] = 1,
    ACTIONS(336), 1,
      sym__eol,
  [1434] = 1,
    ACTIONS(338), 1,
      anon_sym_RBRACE,
  [1438] = 1,
    ACTIONS(340), 1,
      sym_identifier,
  [1442] = 1,
    ACTIONS(342), 1,
      sym__eol,
  [1446] = 1,
    ACTIONS(344), 1,
      anon_sym_RBRACE,
  [1450] = 1,
    ACTIONS(346), 1,
      sym__eol,
  [1454] = 1,
    ACTIONS(348), 1,
      anon_sym_RBRACE,
  [1458] = 1,
    ACTIONS(350), 1,
      sym_identifier,
  [1462] = 1,
    ACTIONS(352), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 126,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 210,
  [SMALL_STATE(8)] = 243,
  [SMALL_STATE(9)] = 276,
  [SMALL_STATE(10)] = 309,
  [SMALL_STATE(11)] = 342,
  [SMALL_STATE(12)] = 375,
  [SMALL_STATE(13)] = 408,
  [SMALL_STATE(14)] = 441,
  [SMALL_STATE(15)] = 474,
  [SMALL_STATE(16)] = 489,
  [SMALL_STATE(17)] = 504,
  [SMALL_STATE(18)] = 519,
  [SMALL_STATE(19)] = 534,
  [SMALL_STATE(20)] = 549,
  [SMALL_STATE(21)] = 564,
  [SMALL_STATE(22)] = 579,
  [SMALL_STATE(23)] = 594,
  [SMALL_STATE(24)] = 609,
  [SMALL_STATE(25)] = 624,
  [SMALL_STATE(26)] = 639,
  [SMALL_STATE(27)] = 654,
  [SMALL_STATE(28)] = 669,
  [SMALL_STATE(29)] = 684,
  [SMALL_STATE(30)] = 698,
  [SMALL_STATE(31)] = 712,
  [SMALL_STATE(32)] = 726,
  [SMALL_STATE(33)] = 740,
  [SMALL_STATE(34)] = 754,
  [SMALL_STATE(35)] = 768,
  [SMALL_STATE(36)] = 781,
  [SMALL_STATE(37)] = 794,
  [SMALL_STATE(38)] = 807,
  [SMALL_STATE(39)] = 828,
  [SMALL_STATE(40)] = 841,
  [SMALL_STATE(41)] = 854,
  [SMALL_STATE(42)] = 867,
  [SMALL_STATE(43)] = 880,
  [SMALL_STATE(44)] = 893,
  [SMALL_STATE(45)] = 914,
  [SMALL_STATE(46)] = 932,
  [SMALL_STATE(47)] = 954,
  [SMALL_STATE(48)] = 972,
  [SMALL_STATE(49)] = 990,
  [SMALL_STATE(50)] = 1008,
  [SMALL_STATE(51)] = 1026,
  [SMALL_STATE(52)] = 1048,
  [SMALL_STATE(53)] = 1070,
  [SMALL_STATE(54)] = 1088,
  [SMALL_STATE(55)] = 1106,
  [SMALL_STATE(56)] = 1121,
  [SMALL_STATE(57)] = 1132,
  [SMALL_STATE(58)] = 1146,
  [SMALL_STATE(59)] = 1158,
  [SMALL_STATE(60)] = 1172,
  [SMALL_STATE(61)] = 1180,
  [SMALL_STATE(62)] = 1194,
  [SMALL_STATE(63)] = 1206,
  [SMALL_STATE(64)] = 1214,
  [SMALL_STATE(65)] = 1227,
  [SMALL_STATE(66)] = 1240,
  [SMALL_STATE(67)] = 1253,
  [SMALL_STATE(68)] = 1266,
  [SMALL_STATE(69)] = 1272,
  [SMALL_STATE(70)] = 1282,
  [SMALL_STATE(71)] = 1292,
  [SMALL_STATE(72)] = 1302,
  [SMALL_STATE(73)] = 1312,
  [SMALL_STATE(74)] = 1319,
  [SMALL_STATE(75)] = 1326,
  [SMALL_STATE(76)] = 1333,
  [SMALL_STATE(77)] = 1340,
  [SMALL_STATE(78)] = 1347,
  [SMALL_STATE(79)] = 1354,
  [SMALL_STATE(80)] = 1361,
  [SMALL_STATE(81)] = 1368,
  [SMALL_STATE(82)] = 1375,
  [SMALL_STATE(83)] = 1382,
  [SMALL_STATE(84)] = 1386,
  [SMALL_STATE(85)] = 1390,
  [SMALL_STATE(86)] = 1394,
  [SMALL_STATE(87)] = 1398,
  [SMALL_STATE(88)] = 1402,
  [SMALL_STATE(89)] = 1406,
  [SMALL_STATE(90)] = 1410,
  [SMALL_STATE(91)] = 1414,
  [SMALL_STATE(92)] = 1418,
  [SMALL_STATE(93)] = 1422,
  [SMALL_STATE(94)] = 1426,
  [SMALL_STATE(95)] = 1430,
  [SMALL_STATE(96)] = 1434,
  [SMALL_STATE(97)] = 1438,
  [SMALL_STATE(98)] = 1442,
  [SMALL_STATE(99)] = 1446,
  [SMALL_STATE(100)] = 1450,
  [SMALL_STATE(101)] = 1454,
  [SMALL_STATE(102)] = 1458,
  [SMALL_STATE(103)] = 1462,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_class, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_ref, 3, 0, 9),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_class, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quantifier, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_class, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 4),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 11),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 10),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 5),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 2, 0, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, 0, 13),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unknown_directive, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_def, 4, 0, 9),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_def, 4, 0, 8),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error_directive, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_def, 5, 0, 8),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unknown_directive, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_def, 5, 0, 9),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error_directive, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [200] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_char_class_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_char_class_repeat1, 2, 0, 0),
  [205] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_char_class_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__char_class_item, 1, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_range, 3, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 3),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 3),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble, 1, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [265] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_epilogue, 1, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [280] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regex, 2, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regex, 2, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [300] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [304] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regex, 3, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regex, 3, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 12),
  [318] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 1),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 6),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 7),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_leg(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "leg",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
