/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 116
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 16
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_section_separator = 1,
  sym__raw_line = 2,
  sym_blank_line = 3,
  sym_comment = 4,
  sym__eol = 5,
  anon_sym_MACRO = 6,
  anon_sym_STATE = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_UNKNOWN = 10,
  anon_sym_ERROR = 11,
  anon_sym_RULE = 12,
  sym_priority = 13,
  sym_identifier = 14,
  sym_action = 15,
  anon_sym_SLASH = 16,
  anon_sym_LPAREN = 17,
  anon_sym_RPAREN = 18,
  anon_sym_STAR = 19,
  anon_sym_PLUS = 20,
  anon_sym_QMARK = 21,
  anon_sym_COMMA = 22,
  sym_number = 23,
  sym_alternation_bar = 24,
  sym_wildcard = 25,
  anon_sym_LBRACK = 26,
  anon_sym_CARET = 27,
  anon_sym_RBRACK = 28,
  anon_sym_DASH = 29,
  sym_escape = 30,
  sym_codepoint_escape = 31,
  sym_literal_char = 32,
  anon_sym_DQUOTE = 33,
  aux_sym_string_literal_token1 = 34,
  sym_source_file = 35,
  sym_preamble = 36,
  sym_epilogue = 37,
  sym_macro_def = 38,
  sym_state_def = 39,
  sym_unknown_directive = 40,
  sym_error_directive = 41,
  sym_rule = 42,
  sym__pattern = 43,
  sym_regex = 44,
  sym__regex_term = 45,
  sym_group = 46,
  sym_quantifier = 47,
  sym_bound_quantifier = 48,
  sym_char_class = 49,
  sym__char_class_item = 50,
  sym_char_range = 51,
  sym_macro_ref = 52,
  sym_string_literal = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_preamble_repeat1 = 55,
  aux_sym_state_def_repeat1 = 56,
  aux_sym_regex_repeat1 = 57,
  aux_sym_char_class_repeat1 = 58,
  aux_sym_string_literal_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_section_separator] = "section_separator",
  [sym__raw_line] = "_raw_line",
  [sym_blank_line] = "blank_line",
  [sym_comment] = "comment",
  [sym__eol] = "_eol",
  [anon_sym_MACRO] = "MACRO",
  [anon_sym_STATE] = "STATE",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_UNKNOWN] = "UNKNOWN",
  [anon_sym_ERROR] = "ERROR",
  [anon_sym_RULE] = "RULE",
  [sym_priority] = "priority",
  [sym_identifier] = "identifier",
  [sym_action] = "action",
  [anon_sym_SLASH] = "/",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COMMA] = ",",
  [sym_number] = "number",
  [sym_alternation_bar] = "alternation_bar",
  [sym_wildcard] = "wildcard",
  [anon_sym_LBRACK] = "[",
  [anon_sym_CARET] = "^",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH] = "-",
  [sym_escape] = "escape",
  [sym_codepoint_escape] = "codepoint_escape",
  [sym_literal_char] = "literal_char",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_source_file] = "source_file",
  [sym_preamble] = "preamble",
  [sym_epilogue] = "epilogue",
  [sym_macro_def] = "macro_def",
  [sym_state_def] = "state_def",
  [sym_unknown_directive] = "unknown_directive",
  [sym_error_directive] = "error_directive",
  [sym_rule] = "rule",
  [sym__pattern] = "_pattern",
  [sym_regex] = "regex",
  [sym__regex_term] = "_regex_term",
  [sym_group] = "group",
  [sym_quantifier] = "quantifier",
  [sym_bound_quantifier] = "bound_quantifier",
  [sym_char_class] = "char_class",
  [sym__char_class_item] = "_char_class_item",
  [sym_char_range] = "char_range",
  [sym_macro_ref] = "macro_ref",
  [sym_string_literal] = "string_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_preamble_repeat1] = "preamble_repeat1",
  [aux_sym_state_def_repeat1] = "state_def_repeat1",
  [aux_sym_regex_repeat1] = "regex_repeat1",
  [aux_sym_char_class_repeat1] = "char_class_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_section_separator] = sym_section_separator,
  [sym__raw_line] = sym__raw_line,
  [sym_blank_line] = sym_blank_line,
  [sym_comment] = sym_comment,
  [sym__eol] = sym__eol,
  [anon_sym_MACRO] = anon_sym_MACRO,
  [anon_sym_STATE] = anon_sym_STATE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_UNKNOWN] = anon_sym_UNKNOWN,
  [anon_sym_ERROR] = anon_sym_ERROR,
  [anon_sym_RULE] = anon_sym_RULE,
  [sym_priority] = sym_priority,
  [sym_identifier] = sym_identifier,
  [sym_action] = sym_action,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_number] = sym_number,
  [sym_alternation_bar] = sym_alternation_bar,
  [sym_wildcard] = sym_wildcard,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_escape] = sym_escape,
  [sym_codepoint_escape] = sym_codepoint_escape,
  [sym_literal_char] = sym_literal_char,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_source_file] = sym_source_file,
  [sym_preamble] = sym_preamble,
  [sym_epilogue] = sym_epilogue,
  [sym_macro_def] = sym_macro_def,
  [sym_state_def] = sym_state_def,
  [sym_unknown_directive] = sym_unknown_directive,
  [sym_error_directive] = sym_error_directive,
  [sym_rule] = sym_rule,
  [sym__pattern] = sym__pattern,
  [sym_regex] = sym_regex,
  [sym__regex_term] = sym__regex_term,
  [sym_group] = sym_group,
  [sym_quantifier] = sym_quantifier,
  [sym_bound_quantifier] = sym_bound_quantifier,
  [sym_char_class] = sym_char_class,
  [sym__char_class_item] = sym__char_class_item,
  [sym_char_range] = sym_char_range,
  [sym_macro_ref] = sym_macro_ref,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_preamble_repeat1] = aux_sym_preamble_repeat1,
  [aux_sym_state_def_repeat1] = aux_sym_state_def_repeat1,
  [aux_sym_regex_repeat1] = aux_sym_regex_repeat1,
  [aux_sym_char_class_repeat1] = aux_sym_char_class_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_section_separator] = {
    .visible = true,
    .named = true,
  },
  [sym__raw_line] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_MACRO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UNKNOWN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ERROR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RULE] = {
    .visible = true,
    .named = false,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_alternation_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_codepoint_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_preamble] = {
    .visible = true,
    .named = true,
  },
  [sym_epilogue] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_def] = {
    .visible = true,
    .named = true,
  },
  [sym_state_def] = {
    .visible = true,
    .named = true,
  },
  [sym_unknown_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_error_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [sym__regex_term] = {
    .visible = false,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_bound_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_char_class] = {
    .visible = true,
    .named = true,
  },
  [sym__char_class_item] = {
    .visible = false,
    .named = true,
  },
  [sym_char_range] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preamble_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_state_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regex_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_char_class_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_action = 1,
  field_epilogue = 2,
  field_max = 3,
  field_min = 4,
  field_name = 5,
  field_pattern = 6,
  field_preamble = 7,
  field_priority = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_action] = "action",
  [field_epilogue] = "epilogue",
  [field_max] = "max",
  [field_min] = "min",
  [field_name] = "name",
  [field_pattern] = "pattern",
  [field_preamble] = "preamble",
  [field_priority] = "priority",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 1},
  [10] = {.index = 12, .length = 2},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 1},
  [13] = {.index = 17, .length = 2},
  [14] = {.index = 19, .length = 3},
  [15] = {.index = 22, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_epilogue, 2},
  [1] =
    {field_pattern, 0},
  [2] =
    {field_preamble, 0},
  [3] =
    {field_pattern, 1},
  [4] =
    {field_action, 1},
    {field_pattern, 0},
  [6] =
    {field_epilogue, 3},
  [7] =
    {field_epilogue, 3},
    {field_preamble, 0},
  [9] =
    {field_name, 1},
    {field_pattern, 2},
  [11] =
    {field_name, 1},
  [12] =
    {field_pattern, 2},
    {field_priority, 1},
  [14] =
    {field_action, 2},
    {field_pattern, 1},
  [16] =
    {field_min, 1},
  [17] =
    {field_epilogue, 4},
    {field_preamble, 0},
  [19] =
    {field_action, 3},
    {field_pattern, 2},
    {field_priority, 1},
  [22] =
    {field_max, 3},
    {field_min, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 10,
  [14] = 6,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 19,
  [28] = 28,
  [29] = 20,
  [30] = 21,
  [31] = 22,
  [32] = 23,
  [33] = 28,
  [34] = 24,
  [35] = 25,
  [36] = 26,
  [37] = 18,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 48,
  [54] = 54,
  [55] = 55,
  [56] = 55,
  [57] = 57,
  [58] = 58,
  [59] = 58,
  [60] = 57,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 22,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 75,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 80,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 90,
  [93] = 89,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 106,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 102,
  [114] = 106,
  [115] = 115,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(48);
      ADVANCE_MAP(
        '\n', 53,
        '\r', 1,
        '"', 96,
        '%', 15,
        '(', 68,
        ')', 69,
        '*', 70,
        '+', 71,
        ',', 73,
        '-', 80,
        '.', 76,
        '/', 67,
        '?', 72,
        'E', 34,
        'M', 19,
        'R', 38,
        'S', 36,
        'U', 26,
        '[', 77,
        '\\', 43,
        ']', 79,
        '^', 78,
        '{', 58,
        '|', 75,
        '}', 59,
        '\t', 2,
        ' ', 2,
        '#', 4,
        ';', 4,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(53);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 53,
        '\r', 1,
        '"', 96,
        '%', 15,
        '(', 68,
        ')', 69,
        '*', 70,
        '+', 71,
        ',', 73,
        '-', 80,
        '.', 76,
        '/', 67,
        '?', 72,
        'E', 34,
        'M', 19,
        'R', 38,
        'S', 36,
        'U', 26,
        '[', 77,
        '\\', 43,
        ']', 79,
        '^', 78,
        '{', 58,
        '|', 75,
        '}', 59,
        '\t', 2,
        ' ', 2,
        '#', 4,
        ';', 4,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 53,
        '\r', 1,
        '"', 96,
        '%', 15,
        '-', 45,
        '/', 67,
        'E', 34,
        'M', 19,
        'R', 38,
        'S', 36,
        'U', 26,
        '}', 59,
        '\t', 3,
        ' ', 3,
        '#', 4,
        ';', 4,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(49);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '%') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '%') ADVANCE(51);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(55);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 14:
      if (lookahead == '"') ADVANCE(96);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(97);
      END_STATE();
    case 15:
      if (lookahead == '%') ADVANCE(50);
      END_STATE();
    case 16:
      ADVANCE_MAP(
        '(', 68,
        ')', 69,
        '*', 70,
        '+', 71,
        '.', 76,
        '?', 72,
        '[', 77,
        '\\', 95,
        '{', 58,
        '|', 75,
        '\t', 89,
        ' ', 89,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 17:
      ADVANCE_MAP(
        '(', 68,
        '*', 70,
        '+', 71,
        '.', 76,
        '/', 67,
        '?', 72,
        '[', 77,
        '\\', 95,
        '{', 58,
        '|', 75,
        '\t', 90,
        ' ', 90,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(80);
      if (lookahead == '\\') ADVANCE(95);
      if (lookahead == ']') ADVANCE(79);
      if (lookahead == '{') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 19:
      if (lookahead == 'A') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'A') ADVANCE(37);
      END_STATE();
    case 21:
      if (lookahead == 'C') ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(62);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(57);
      END_STATE();
    case 24:
      if (lookahead == 'K') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 'L') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == 'N') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == 'N') ADVANCE(60);
      END_STATE();
    case 28:
      if (lookahead == 'N') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'O') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == 'O') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 'O') ADVANCE(33);
      END_STATE();
    case 32:
      if (lookahead == 'R') ADVANCE(31);
      END_STATE();
    case 33:
      if (lookahead == 'R') ADVANCE(61);
      END_STATE();
    case 34:
      if (lookahead == 'R') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'R') ADVANCE(29);
      END_STATE();
    case 36:
      if (lookahead == 'T') ADVANCE(20);
      END_STATE();
    case 37:
      if (lookahead == 'T') ADVANCE(23);
      END_STATE();
    case 38:
      if (lookahead == 'U') ADVANCE(25);
      END_STATE();
    case 39:
      if (lookahead == 'W') ADVANCE(27);
      END_STATE();
    case 40:
      if (lookahead == '\\') ADVANCE(95);
      if (lookahead == ']') ADVANCE(79);
      if (lookahead == '^') ADVANCE(78);
      if (lookahead == '{') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 41:
      if (lookahead == '\\') ADVANCE(95);
      if (lookahead == ']') ADVANCE(79);
      if (lookahead == '{') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 42:
      if (lookahead == '\\') ADVANCE(95);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(82);
      if (lookahead == 'x') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(81);
      END_STATE();
    case 44:
      if (lookahead == '}') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(44);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(44);
      END_STATE();
    case 47:
      if (eof) ADVANCE(48);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_section_separator);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_section_separator);
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_section_separator);
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__raw_line);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_MACRO);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_STATE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_UNKNOWN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_ERROR);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RULE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_priority);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_action);
      if (lookahead == '\r') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_action);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_alternation_bar);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_escape);
      if (lookahead == '{') ADVANCE(46);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_escape);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(81);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_escape);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(83);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_escape);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_escape);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_codepoint_escape);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_literal_char);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_literal_char);
      ADVANCE_MAP(
        '(', 68,
        ')', 69,
        '*', 70,
        '+', 71,
        '.', 76,
        '?', 72,
        '[', 77,
        '\\', 95,
        '{', 58,
        '|', 75,
        '\t', 89,
        ' ', 89,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_literal_char);
      ADVANCE_MAP(
        '(', 68,
        '*', 70,
        '+', 71,
        '.', 76,
        '/', 67,
        '?', 72,
        '[', 77,
        '\\', 95,
        '{', 58,
        '|', 75,
        '\t', 90,
        ' ', 90,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == '-') ADVANCE(80);
      if (lookahead == '\\') ADVANCE(95);
      if (lookahead == ']') ADVANCE(79);
      if (lookahead == '{') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == '\\') ADVANCE(95);
      if (lookahead == ']') ADVANCE(79);
      if (lookahead == '^') ADVANCE(78);
      if (lookahead == '{') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == '\\') ADVANCE(95);
      if (lookahead == ']') ADVANCE(79);
      if (lookahead == '{') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == '\\') ADVANCE(95);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_literal_char);
      if (lookahead == 'u') ADVANCE(82);
      if (lookahead == 'x') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(81);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(97);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 17},
  [21] = {.lex_state = 17},
  [22] = {.lex_state = 17},
  [23] = {.lex_state = 17},
  [24] = {.lex_state = 17},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 17},
  [27] = {.lex_state = 17},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 17},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 17},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 40},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 40},
  [54] = {.lex_state = 41},
  [55] = {.lex_state = 41},
  [56] = {.lex_state = 41},
  [57] = {.lex_state = 41},
  [58] = {.lex_state = 41},
  [59] = {.lex_state = 41},
  [60] = {.lex_state = 41},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 18},
  [63] = {.lex_state = 41},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 14},
  [66] = {.lex_state = 14},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 41},
  [69] = {.lex_state = 14},
  [70] = {.lex_state = 47},
  [71] = {.lex_state = 47},
  [72] = {.lex_state = 47},
  [73] = {.lex_state = 47},
  [74] = {.lex_state = 42},
  [75] = {.lex_state = 47},
  [76] = {.lex_state = 47},
  [77] = {.lex_state = 7},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 12},
  [80] = {.lex_state = 13},
  [81] = {.lex_state = 12},
  [82] = {.lex_state = 12},
  [83] = {.lex_state = 12},
  [84] = {.lex_state = 12},
  [85] = {.lex_state = 12},
  [86] = {.lex_state = 13},
  [87] = {.lex_state = 12},
  [88] = {.lex_state = 12},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 12},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 12},
  [95] = {.lex_state = 13},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 13},
  [98] = {.lex_state = 13},
  [99] = {.lex_state = 13},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 13},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 13},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 13},
  [108] = {.lex_state = 13},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 13},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_section_separator] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
    [anon_sym_MACRO] = ACTIONS(1),
    [anon_sym_STATE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_UNKNOWN] = ACTIONS(1),
    [anon_sym_ERROR] = ACTIONS(1),
    [anon_sym_RULE] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_alternation_bar] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [sym_codepoint_escape] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(112),
    [sym_preamble] = STATE(100),
    [aux_sym_preamble_repeat1] = STATE(78),
    [sym_section_separator] = ACTIONS(3),
    [sym__raw_line] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(7), 1,
      sym_section_separator,
    ACTIONS(11), 1,
      anon_sym_MACRO,
    ACTIONS(13), 1,
      anon_sym_STATE,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 2,
      sym_blank_line,
      sym_comment,
    STATE(83), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(4), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [42] = 8,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_SLASH,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      sym_bound_quantifier,
    ACTIONS(31), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(33), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(7), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [78] = 11,
    ACTIONS(11), 1,
      anon_sym_MACRO,
    ACTIONS(13), 1,
      anon_sym_STATE,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_section_separator,
    ACTIONS(39), 2,
      sym_blank_line,
      sym_comment,
    STATE(83), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(8), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [120] = 11,
    ACTIONS(11), 1,
      anon_sym_MACRO,
    ACTIONS(13), 1,
      anon_sym_STATE,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      sym_section_separator,
    ACTIONS(43), 2,
      sym_blank_line,
      sym_comment,
    STATE(83), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(9), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [162] = 8,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    STATE(28), 1,
      sym_bound_quantifier,
    ACTIONS(51), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(53), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(10), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [198] = 8,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_SLASH,
    STATE(33), 1,
      sym_bound_quantifier,
    ACTIONS(31), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(59), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(12), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [234] = 11,
    ACTIONS(61), 1,
      sym_section_separator,
    ACTIONS(66), 1,
      anon_sym_MACRO,
    ACTIONS(69), 1,
      anon_sym_STATE,
    ACTIONS(72), 1,
      anon_sym_UNKNOWN,
    ACTIONS(75), 1,
      anon_sym_ERROR,
    ACTIONS(78), 1,
      anon_sym_RULE,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    ACTIONS(84), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 2,
      sym_blank_line,
      sym_comment,
    STATE(83), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(8), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [276] = 11,
    ACTIONS(11), 1,
      anon_sym_MACRO,
    ACTIONS(13), 1,
      anon_sym_STATE,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      sym_section_separator,
    ACTIONS(39), 2,
      sym_blank_line,
      sym_comment,
    STATE(83), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(8), 6,
      sym_macro_def,
      sym_state_def,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_source_file_repeat1,
  [318] = 8,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_bound_quantifier,
    ACTIONS(51), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(91), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(11), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [354] = 8,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    STATE(28), 1,
      sym_bound_quantifier,
    ACTIONS(101), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(104), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(11), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [390] = 8,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      sym_bound_quantifier,
    ACTIONS(116), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(119), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(12), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [426] = 8,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_bound_quantifier,
    ACTIONS(51), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(91), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(11), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [462] = 8,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_bound_quantifier,
    ACTIONS(51), 3,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
    ACTIONS(129), 5,
      sym_alternation_bar,
      sym_wildcard,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(13), 6,
      sym__regex_term,
      sym_group,
      sym_quantifier,
      sym_char_class,
      sym_macro_ref,
      aux_sym_regex_repeat1,
  [498] = 9,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(131), 2,
      sym_blank_line,
      sym_comment,
    STATE(83), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(16), 4,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_state_def_repeat1,
  [532] = 9,
    ACTIONS(15), 1,
      anon_sym_UNKNOWN,
    ACTIONS(17), 1,
      anon_sym_ERROR,
    ACTIONS(19), 1,
      anon_sym_RULE,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    ACTIONS(135), 2,
      sym_blank_line,
      sym_comment,
    STATE(83), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(17), 4,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_state_def_repeat1,
  [566] = 9,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    ACTIONS(144), 1,
      anon_sym_UNKNOWN,
    ACTIONS(147), 1,
      anon_sym_ERROR,
    ACTIONS(150), 1,
      anon_sym_RULE,
    ACTIONS(153), 1,
      anon_sym_SLASH,
    ACTIONS(156), 1,
      anon_sym_DQUOTE,
    ACTIONS(139), 2,
      sym_blank_line,
      sym_comment,
    STATE(83), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
    STATE(17), 4,
      sym_unknown_directive,
      sym_error_directive,
      sym_rule,
      aux_sym_state_def_repeat1,
  [600] = 1,
    ACTIONS(159), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [615] = 1,
    ACTIONS(161), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [630] = 1,
    ACTIONS(163), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [645] = 1,
    ACTIONS(165), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [660] = 1,
    ACTIONS(167), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [675] = 1,
    ACTIONS(169), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [690] = 1,
    ACTIONS(171), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [705] = 1,
    ACTIONS(173), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [720] = 1,
    ACTIONS(175), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [735] = 1,
    ACTIONS(161), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [750] = 1,
    ACTIONS(177), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [765] = 1,
    ACTIONS(163), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [780] = 1,
    ACTIONS(165), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [795] = 1,
    ACTIONS(167), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [810] = 1,
    ACTIONS(169), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [825] = 1,
    ACTIONS(177), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [840] = 1,
    ACTIONS(171), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [855] = 1,
    ACTIONS(173), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [870] = 1,
    ACTIONS(175), 12,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [885] = 1,
    ACTIONS(159), 12,
      anon_sym_LBRACE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_QMARK,
      sym_alternation_bar,
      sym_wildcard,
      anon_sym_LBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [900] = 1,
    ACTIONS(179), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [914] = 1,
    ACTIONS(181), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [928] = 1,
    ACTIONS(183), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [942] = 1,
    ACTIONS(185), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [956] = 1,
    ACTIONS(187), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [970] = 1,
    ACTIONS(189), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [984] = 1,
    ACTIONS(191), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [998] = 1,
    ACTIONS(193), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [1012] = 1,
    ACTIONS(195), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [1026] = 1,
    ACTIONS(197), 11,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_RBRACE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [1040] = 5,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(201), 1,
      anon_sym_CARET,
    ACTIONS(203), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(58), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1061] = 1,
    ACTIONS(207), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [1074] = 1,
    ACTIONS(209), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [1087] = 1,
    ACTIONS(211), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [1100] = 1,
    ACTIONS(213), 10,
      sym_section_separator,
      sym_blank_line,
      sym_comment,
      anon_sym_MACRO,
      anon_sym_STATE,
      anon_sym_UNKNOWN,
      anon_sym_ERROR,
      anon_sym_RULE,
      anon_sym_SLASH,
      anon_sym_DQUOTE,
  [1113] = 5,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(215), 1,
      anon_sym_CARET,
    ACTIONS(217), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(59), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1134] = 4,
    ACTIONS(219), 1,
      anon_sym_LBRACE,
    ACTIONS(222), 1,
      anon_sym_RBRACK,
    ACTIONS(224), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(54), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1152] = 4,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(57), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1170] = 4,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(229), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(60), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1188] = 4,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(231), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(54), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1206] = 4,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(227), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(54), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1224] = 4,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(229), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(54), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1242] = 4,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(233), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
    STATE(54), 4,
      sym__char_class_item,
      sym_char_range,
      sym_macro_ref,
      aux_sym_char_class_repeat1,
  [1260] = 4,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(235), 1,
      sym_priority,
    STATE(85), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
  [1275] = 2,
    ACTIONS(239), 1,
      anon_sym_DASH,
    ACTIONS(237), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [1286] = 1,
    ACTIONS(241), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [1294] = 3,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(87), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
  [1306] = 4,
    ACTIONS(245), 1,
      anon_sym_DQUOTE,
    ACTIONS(247), 1,
      aux_sym_string_literal_token1,
    STATE(66), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(243), 2,
      sym_escape,
      sym_codepoint_escape,
  [1320] = 4,
    ACTIONS(252), 1,
      anon_sym_DQUOTE,
    ACTIONS(254), 1,
      aux_sym_string_literal_token1,
    STATE(66), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(249), 2,
      sym_escape,
      sym_codepoint_escape,
  [1334] = 3,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(84), 3,
      sym__pattern,
      sym_regex,
      sym_string_literal,
  [1346] = 1,
    ACTIONS(167), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [1354] = 4,
    ACTIONS(259), 1,
      anon_sym_DQUOTE,
    ACTIONS(261), 1,
      aux_sym_string_literal_token1,
    STATE(65), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(257), 2,
      sym_escape,
      sym_codepoint_escape,
  [1368] = 4,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
    ACTIONS(265), 1,
      sym__raw_line,
    STATE(76), 1,
      aux_sym_preamble_repeat1,
    STATE(111), 1,
      sym_epilogue,
  [1381] = 4,
    ACTIONS(265), 1,
      sym__raw_line,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
    STATE(76), 1,
      aux_sym_preamble_repeat1,
    STATE(96), 1,
      sym_epilogue,
  [1394] = 4,
    ACTIONS(265), 1,
      sym__raw_line,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
    STATE(76), 1,
      aux_sym_preamble_repeat1,
    STATE(110), 1,
      sym_epilogue,
  [1407] = 4,
    ACTIONS(265), 1,
      sym__raw_line,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
    STATE(76), 1,
      aux_sym_preamble_repeat1,
    STATE(103), 1,
      sym_epilogue,
  [1420] = 1,
    ACTIONS(273), 3,
      sym_escape,
      sym_codepoint_escape,
      sym_literal_char,
  [1426] = 3,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
    ACTIONS(277), 1,
      sym__raw_line,
    STATE(75), 1,
      aux_sym_preamble_repeat1,
  [1436] = 3,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
    ACTIONS(282), 1,
      sym__raw_line,
    STATE(75), 1,
      aux_sym_preamble_repeat1,
  [1446] = 3,
    ACTIONS(275), 1,
      sym_section_separator,
    ACTIONS(284), 1,
      sym__raw_line,
    STATE(77), 1,
      aux_sym_preamble_repeat1,
  [1456] = 3,
    ACTIONS(287), 1,
      sym_section_separator,
    ACTIONS(289), 1,
      sym__raw_line,
    STATE(77), 1,
      aux_sym_preamble_repeat1,
  [1466] = 2,
    ACTIONS(291), 1,
      sym__eol,
    ACTIONS(293), 1,
      sym_action,
  [1473] = 2,
    ACTIONS(295), 1,
      sym_identifier,
    ACTIONS(297), 1,
      sym_number,
  [1480] = 2,
    ACTIONS(299), 1,
      sym__eol,
    ACTIONS(301), 1,
      sym_action,
  [1487] = 2,
    ACTIONS(303), 1,
      sym__eol,
    ACTIONS(305), 1,
      sym_action,
  [1494] = 2,
    ACTIONS(307), 1,
      sym__eol,
    ACTIONS(309), 1,
      sym_action,
  [1501] = 2,
    ACTIONS(311), 1,
      sym__eol,
    ACTIONS(313), 1,
      sym_action,
  [1508] = 2,
    ACTIONS(315), 1,
      sym__eol,
    ACTIONS(317), 1,
      sym_action,
  [1515] = 2,
    ACTIONS(319), 1,
      sym_identifier,
    ACTIONS(321), 1,
      sym_number,
  [1522] = 2,
    ACTIONS(323), 1,
      sym__eol,
    ACTIONS(325), 1,
      sym_action,
  [1529] = 2,
    ACTIONS(327), 1,
      sym__eol,
    ACTIONS(329), 1,
      sym_action,
  [1536] = 2,
    ACTIONS(331), 1,
      anon_sym_RBRACE,
    ACTIONS(333), 1,
      sym_number,
  [1543] = 2,
    ACTIONS(335), 1,
      anon_sym_RBRACE,
    ACTIONS(337), 1,
      anon_sym_COMMA,
  [1550] = 2,
    ACTIONS(339), 1,
      sym__eol,
    ACTIONS(341), 1,
      sym_action,
  [1557] = 2,
    ACTIONS(343), 1,
      anon_sym_RBRACE,
    ACTIONS(345), 1,
      anon_sym_COMMA,
  [1564] = 2,
    ACTIONS(347), 1,
      anon_sym_RBRACE,
    ACTIONS(349), 1,
      sym_number,
  [1571] = 2,
    ACTIONS(351), 1,
      sym__eol,
    ACTIONS(353), 1,
      sym_action,
  [1578] = 1,
    ACTIONS(355), 1,
      sym__eol,
  [1582] = 1,
    ACTIONS(357), 1,
      ts_builtin_sym_end,
  [1586] = 1,
    ACTIONS(359), 1,
      sym__eol,
  [1590] = 1,
    ACTIONS(361), 1,
      sym_identifier,
  [1594] = 1,
    ACTIONS(363), 1,
      sym_identifier,
  [1598] = 1,
    ACTIONS(365), 1,
      sym_section_separator,
  [1602] = 1,
    ACTIONS(367), 1,
      sym__eol,
  [1606] = 1,
    ACTIONS(369), 1,
      anon_sym_RBRACE,
  [1610] = 1,
    ACTIONS(371), 1,
      ts_builtin_sym_end,
  [1614] = 1,
    ACTIONS(373), 1,
      anon_sym_LBRACE,
  [1618] = 1,
    ACTIONS(375), 1,
      sym__eol,
  [1622] = 1,
    ACTIONS(377), 1,
      anon_sym_RBRACE,
  [1626] = 1,
    ACTIONS(379), 1,
      sym_identifier,
  [1630] = 1,
    ACTIONS(381), 1,
      sym__eol,
  [1634] = 1,
    ACTIONS(383), 1,
      anon_sym_RBRACE,
  [1638] = 1,
    ACTIONS(385), 1,
      ts_builtin_sym_end,
  [1642] = 1,
    ACTIONS(387), 1,
      ts_builtin_sym_end,
  [1646] = 1,
    ACTIONS(389), 1,
      ts_builtin_sym_end,
  [1650] = 1,
    ACTIONS(391), 1,
      anon_sym_RBRACE,
  [1654] = 1,
    ACTIONS(393), 1,
      anon_sym_RBRACE,
  [1658] = 1,
    ACTIONS(395), 1,
      sym__eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 162,
  [SMALL_STATE(7)] = 198,
  [SMALL_STATE(8)] = 234,
  [SMALL_STATE(9)] = 276,
  [SMALL_STATE(10)] = 318,
  [SMALL_STATE(11)] = 354,
  [SMALL_STATE(12)] = 390,
  [SMALL_STATE(13)] = 426,
  [SMALL_STATE(14)] = 462,
  [SMALL_STATE(15)] = 498,
  [SMALL_STATE(16)] = 532,
  [SMALL_STATE(17)] = 566,
  [SMALL_STATE(18)] = 600,
  [SMALL_STATE(19)] = 615,
  [SMALL_STATE(20)] = 630,
  [SMALL_STATE(21)] = 645,
  [SMALL_STATE(22)] = 660,
  [SMALL_STATE(23)] = 675,
  [SMALL_STATE(24)] = 690,
  [SMALL_STATE(25)] = 705,
  [SMALL_STATE(26)] = 720,
  [SMALL_STATE(27)] = 735,
  [SMALL_STATE(28)] = 750,
  [SMALL_STATE(29)] = 765,
  [SMALL_STATE(30)] = 780,
  [SMALL_STATE(31)] = 795,
  [SMALL_STATE(32)] = 810,
  [SMALL_STATE(33)] = 825,
  [SMALL_STATE(34)] = 840,
  [SMALL_STATE(35)] = 855,
  [SMALL_STATE(36)] = 870,
  [SMALL_STATE(37)] = 885,
  [SMALL_STATE(38)] = 900,
  [SMALL_STATE(39)] = 914,
  [SMALL_STATE(40)] = 928,
  [SMALL_STATE(41)] = 942,
  [SMALL_STATE(42)] = 956,
  [SMALL_STATE(43)] = 970,
  [SMALL_STATE(44)] = 984,
  [SMALL_STATE(45)] = 998,
  [SMALL_STATE(46)] = 1012,
  [SMALL_STATE(47)] = 1026,
  [SMALL_STATE(48)] = 1040,
  [SMALL_STATE(49)] = 1061,
  [SMALL_STATE(50)] = 1074,
  [SMALL_STATE(51)] = 1087,
  [SMALL_STATE(52)] = 1100,
  [SMALL_STATE(53)] = 1113,
  [SMALL_STATE(54)] = 1134,
  [SMALL_STATE(55)] = 1152,
  [SMALL_STATE(56)] = 1170,
  [SMALL_STATE(57)] = 1188,
  [SMALL_STATE(58)] = 1206,
  [SMALL_STATE(59)] = 1224,
  [SMALL_STATE(60)] = 1242,
  [SMALL_STATE(61)] = 1260,
  [SMALL_STATE(62)] = 1275,
  [SMALL_STATE(63)] = 1286,
  [SMALL_STATE(64)] = 1294,
  [SMALL_STATE(65)] = 1306,
  [SMALL_STATE(66)] = 1320,
  [SMALL_STATE(67)] = 1334,
  [SMALL_STATE(68)] = 1346,
  [SMALL_STATE(69)] = 1354,
  [SMALL_STATE(70)] = 1368,
  [SMALL_STATE(71)] = 1381,
  [SMALL_STATE(72)] = 1394,
  [SMALL_STATE(73)] = 1407,
  [SMALL_STATE(74)] = 1420,
  [SMALL_STATE(75)] = 1426,
  [SMALL_STATE(76)] = 1436,
  [SMALL_STATE(77)] = 1446,
  [SMALL_STATE(78)] = 1456,
  [SMALL_STATE(79)] = 1466,
  [SMALL_STATE(80)] = 1473,
  [SMALL_STATE(81)] = 1480,
  [SMALL_STATE(82)] = 1487,
  [SMALL_STATE(83)] = 1494,
  [SMALL_STATE(84)] = 1501,
  [SMALL_STATE(85)] = 1508,
  [SMALL_STATE(86)] = 1515,
  [SMALL_STATE(87)] = 1522,
  [SMALL_STATE(88)] = 1529,
  [SMALL_STATE(89)] = 1536,
  [SMALL_STATE(90)] = 1543,
  [SMALL_STATE(91)] = 1550,
  [SMALL_STATE(92)] = 1557,
  [SMALL_STATE(93)] = 1564,
  [SMALL_STATE(94)] = 1571,
  [SMALL_STATE(95)] = 1578,
  [SMALL_STATE(96)] = 1582,
  [SMALL_STATE(97)] = 1586,
  [SMALL_STATE(98)] = 1590,
  [SMALL_STATE(99)] = 1594,
  [SMALL_STATE(100)] = 1598,
  [SMALL_STATE(101)] = 1602,
  [SMALL_STATE(102)] = 1606,
  [SMALL_STATE(103)] = 1610,
  [SMALL_STATE(104)] = 1614,
  [SMALL_STATE(105)] = 1618,
  [SMALL_STATE(106)] = 1622,
  [SMALL_STATE(107)] = 1626,
  [SMALL_STATE(108)] = 1630,
  [SMALL_STATE(109)] = 1634,
  [SMALL_STATE(110)] = 1638,
  [SMALL_STATE(111)] = 1642,
  [SMALL_STATE(112)] = 1646,
  [SMALL_STATE(113)] = 1650,
  [SMALL_STATE(114)] = 1654,
  [SMALL_STATE(115)] = 1658,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_regex_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_state_def_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bound_quantifier, 5, 0, 15),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_class, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_ref, 3, 0, 9),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bound_quantifier, 3, 0, 12),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_class, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bound_quantifier, 4, 0, 12),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_class, 4, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quantifier, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 2, 0, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error_directive, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 10),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 11),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, 0, 14),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unknown_directive, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error_directive, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 4),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unknown_directive, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 5),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_def, 5, 0, 9),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_def, 4, 0, 9),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_def, 5, 0, 8),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_def, 4, 0, 8),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [219] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_char_class_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_char_class_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_char_class_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__char_class_item, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_range, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [249] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 3),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 3),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_epilogue, 1, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [284] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble, 1, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [303] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regex, 3, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regex, 3, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [315] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [323] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regex, 2, 0, 0),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regex, 2, 0, 0),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [339] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [351] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 13),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 1),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 6),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 7),
  [389] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_leg(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "leg",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
